Hw04 auth
an-shem/nodejs-homework-rest-api pull request #5
Opened 2022-01-05 20:59 UTC by an-shem

Прошу проверить 4-ю ДЗ

2022-01-06 19:50 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  let contacts = null;
тут можна проще 
```
const filter = { owner: _id }
if (favorite) {
  filter.favorite = favorite
}
const contacts = await Contact.find(filter, '', {
       skip,
       limit: Number(limit),
     }).populate('owner', '_id email subscription');
```

2022-01-06 19:51 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  const skip = (page - 1) * limit;
перед этой строкой было бы хорошо делать валидацию page и limit на число через isNaN

2022-01-06 19:52 UTC, KirillKulakow commented on controllers/users/login.js
> +  const comparePass = bcrypt.compareSync(password, user.password);
тут наверно лучше будет написать по другому
`const comparePass = bcrypt.compareSync(password, (user && user.password) || "");`

2022-01-06 19:53 UTC, KirillKulakow commented on controllers/users/login.js
> +  const comparePass = bcrypt.compareSync(password, user.password);
если юзер не будет найден будет ошибка

2022-01-06 19:55 UTC, KirillKulakow commented
еще нужно внести правки в логику удаления и редактирования контакта
чтобы можно было удалить/редактировать только свой контакт
в фильтр добавить не только ид контакта но и ид собственника

2022-01-06 19:55 UTC, KirillKulakow requested changes
Need fix

2022-01-07 11:41 UTC, an-shem commented on controllers/contacts/getAll.js
> +  let contacts = null;
исправил

2022-01-07 11:41 UTC, an-shem commented on controllers/contacts/getAll.js
> +  const skip = (page - 1) * limit;
сделал валидацию

2022-01-07 11:50 UTC, an-shem commented on controllers/users/login.js
> +  const comparePass = bcrypt.compareSync(password, user.password);
подправил

2022-01-07 13:43 UTC, an-shem commented
Внес поправки, прошу проверить

2022-01-08 11:44 UTC, KirillKulakow commented on controllers/contacts/getById.js
> +  const contact = await Contact.findOne({ _id: contactId, owner: { _id: _id } });
эээ а почему так написал `owner: { _id: _id }`?
оно так работает?
обычно так: Contact.findOne({ _id: contactId, owner:  _id })

2022-01-08 11:44 UTC, KirillKulakow commented on controllers/contacts/removeById.js
> +  const removedСontact = await Contact.findOneAndRemove({ _id: contactId, owner: { _id: _id } });
прошлый коммент

2022-01-08 11:44 UTC, KirillKulakow commented on controllers/contacts/updateById.js
> +  const updateContact = await Contact.findOneAndUpdate({ _id: contactId, owner: { _id: _id } }, req.body, {
прошлый коммент

2022-01-08 11:44 UTC, KirillKulakow commented on controllers/contacts/updateFavorite.js
> +  const updateContact = await Contact.findOneAndUpdate(
прошлый коммент

2022-01-08 11:45 UTC, KirillKulakow requested changes
need fix

2022-01-09 12:11 UTC, an-shem commented on controllers/contacts/getById.js
> +  const contact = await Contact.findOne({ _id: contactId, owner: { _id: _id } });
Работает) сам думал что вроде не правильно... Но работает

2022-01-09 12:51 UTC, an-shem commented
Исправил

2022-01-09 19:42 UTC, KirillKulakow approved these changes

2022-01-09 20:13 UTC, merged