Hw06 email
an-shem/nodejs-homework-rest-api pull request #7
Opened 2022-01-10 21:13 UTC by an-shem

Прошу проверить 6-е ДЗ

2022-01-10 22:05 UTC, KirillKulakow commented on controllers/users/reverifyEmail.js
> +  if (user.verify) {
а если user будет undefined?

2022-01-10 22:06 UTC, KirillKulakow requested changes
Need fix

2022-01-10 22:13 UTC, an-shem commented on controllers/users/reverifyEmail.js
> +  if (user.verify) {
точно

2022-01-10 22:14 UTC, an-shem commented on controllers/users/reverifyEmail.js
> +  if (user.verify) {
исправил

2022-01-10 22:16 UTC, an-shem commented
Исправил

2022-01-11 06:36 UTC, KirillKulakow approved these changes

2022-01-11 08:14 UTC, merged